PUBLIC_FEEDS = {
    "DanLuu": "https://danluu.com/atom.xml",
    "XKCD": "https://xkcd.com/rss.xml",
    "Paul Graham": "https://filipesilva.github.io/paulgraham-rss/feed.rss",
    "Hillel Wayne": "https://buttondown.com/hillelwayne/rss",
    "Rands in Repose": "https://randsinrepose.com/feed/",
    "Architecture Notes": "https://architecturenotes.co/feed",
    "SlateStarCodex": "https://www.astralcodexten.com/feed",
    "Dynomight": "https://dynomight.net/feed.xml",
    "Squishy Computer": "https://newsletter.squishy.computer/feed",
    "Margins": "https://www.readmargins.com/feed",
    "Robert Heaton": "https://robertheaton.com/feed.xml",
    "PFAB": "https://advancedbeginners.substack.com/feed",
    "Good Reason": "https://goodreason.substack.com/feed",
    "Remains of the Day": "https://eugenewei.substack.com/feed",
    "Everything Studies": "https://everythingstudies.com/feed/",
    "Stirred Blog": "https://stirredblog.com/feed/",
    "Made of Bugs": "https://blog.nelhage.com/atom.xml",
    "Ben Kuhn": "https://www.benkuhn.net/index.xml",
    "Bram Adams": "https://www.bramadams.dev/rss/",
    "Cal Paterson": "https://calpaterson.com/calpaterson.rss",
    "CSV Base": "https://csvbase.com/blog/posts.rss",
    "DHH": "https://world.hey.com/dhh/feed.atom",
    "Jason Fried": "https://world.hey.com/jason/feed.atom",
    "Robert Nystrom": "https://journal.stuffwithstuff.com/rss.xml",
    "WaitButWhy": "https://waitbutwhy.com/feed",
    "Coding Horror": "https://blog.codinghorror.com/rss/",
    "Herman Martinus": "https://herman.bearblog.dev/feed/",
    "Linus Lee": "https://thesephist.com/index.xml",
    "The Sephist": "https://buttondown.com/thesephist/rss",
    "Putanumonit": "https://putanumonit.com/feed/",
    "Facundo Olano": "https://olano.dev/feed.xml",
    "Bits About Money": "https://www.bitsaboutmoney.com/archive/rss/",
}
