PUBLIC_FEEDS = {
    "Alex Chan": "https://alexwlchan.net/atom.xml",
    "Alex Molas": "https://www.alexmolas.com/feed.xml",
    "Architecture Notes": "https://architecturenotes.co/feed",
    "Ben Kuhn": "https://www.benkuhn.net/index.xml",
    "Bits About Money": "https://www.bitsaboutmoney.com/archive/rss/",
    "Cal Paterson": "https://calpaterson.com/calpaterson.rss",
    "Charity Majors": "https://charity.wtf/feed/",
    "CSV Base": "https://csvbase.com/blog/posts.rss",
    "DanLuu": "https://danluu.com/atom.xml",
    "DHH": "https://world.hey.com/dhh/feed.atom",
    "Dynomight": "https://dynomight.net/feed.xml",
    "Eric Fritz": "https://www.eric-fritz.com/index.xml",
    "Eric Zakariasson": "https://anyblockers.com/rss.xml",
    "Ethan Mollick": "https://www.oneusefulthing.org/feed",
    "Eugene Wei": "https://eugenewei.substack.com/feed",
    "Eugene Yan": "https://eugeneyan.com/rss/",
    "Everything Studies": "https://everythingstudies.com/feed/",
    "Facundo Olano": "https://olano.dev/feed.xml",
    "Geoffrey Huntley": "https://ghuntley.com/rss/",
    "Geoffrey Litt": "https://www.geoffreylitt.com/feed.xml",
    "Good Reason": "https://goodreason.substack.com/feed",
    "Grant Slatton": "https://grantslatton.com/rss.xml",
    "Harper Reed": "https://harper.blog/index.xml",
    "Herman Martinus": "https://herman.bearblog.dev/feed/",
    "Hillel Wayne": "https://buttondown.com/hillelwayne/rss",
    "Ink & Switch": "https://www.inkandswitch.com/index.xml",
    "Jason Fried": "https://world.hey.com/jason/feed.atom",
    "Jeff Atwood": "https://blog.codinghorror.com/rss/",
    "John Loeber": "https://loeber.substack.com/feed",
    "Jonas Hietala": "https://www.jonashietala.se/feed.xml",
    "Kevin Simler": "https://feeds.feedburner.com/MeltingAsphalt",
    "Linus Lee": "https://thesephist.com/index.xml",
    "Lukas Petersson": "https://lukaspetersson.com/feed.xml",
    "Margins": "https://www.readmargins.com/feed",
    "Nabeel Qureshi": "https://nabeelqu.co/rss",
    "Narrative Ark": "https://www.narrativeark.xyz/feed",
    "Nelson Elhage": "https://blog.nelhage.com/atom.xml",
    "Paul Graham": "https://filipesilva.github.io/paulgraham-rss/feed.rss",
    "PFAB": "https://advancedbeginners.substack.com/feed",
    "Putanumonit": "https://putanumonit.com/feed/",
    "QNTM": "https://qntm.org/rss.php",
    "Rands in Repose": "https://randsinrepose.com/feed/",
    "Robert Heaton": "https://robertheaton.com/feed.xml",
    "Robert Nystrom": "https://journal.stuffwithstuff.com/rss.xml",
    "Robin Hanson": "https://www.overcomingbias.com/feed",
    "Shrivu Shankar": "https://blog.sshh.io/feed",
    "Simon Willison": "https://simonwillison.net/atom/entries/",
    "SlateStarCodex": "https://www.astralcodexten.com/feed",
    "Squishy Computer": "https://newsletter.squishy.computer/feed",
    "Stephen Wolfram": "https://writings.stephenwolfram.com/feed/",
    "Stirred Blog": "https://stirredblog.com/feed/",
    "The Sephist": "https://buttondown.com/thesephist/rss",
    "WaitButWhy": "https://waitbutwhy.com/feed",
    "Will Larson": "https://lethain.com/feeds.xml",
    "Xe Iaso": "https://xeiaso.net/blog.rss",
    "XKCD": "https://xkcd.com/rss.xml",
}
